Repository pymodbus-dev/pymodbus, pull requests merged in 2022-05, with the labels that each got.

#875 Simplify requirements*.txt
  Makefile
  README.rst
  doc/api/pydoc/build.py
  pymodbus/repl/client/completer.py
  pymodbus/repl/client/main.py
  pymodbus/repl/server/cli.py
  requirements-checks.txt
  requirements-coverage.txt
  requirements-docs.txt
  requirements-tests.txt
  requirements.txt
  setup.cfg
  setup.py
  test/test_datastore.py
  test/test_other_messages.py
  tox.ini
Labels: IN REVIEW

#689 Documentation cleanup and clarification
  doc/source/library/pymodbus.client.asynchronous.async_io.rst
  doc/source/library/pymodbus.client.rst
  pymodbus/bit_read_message.py
  pymodbus/client/asynchronous/async_io/__init__.py
  pymodbus/client/sync.py
  pymodbus/register_read_message.py
Labels: IN REVIEW, 3.x

#709 708 Implement ReadFileRecordRequest.get_response_pdu_size() to ensure complete record
  pymodbus/file_message.py
Labels: Bug, More Information Required
